version: '3.8'
services:
    kamae-challenge:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/app
        ports:
            - '5173:5173'
        command: npm run dev
        environment:
            - NODE_ENV=development
