version: '3.8'
services:
    kamae-challenge:
        build:
            context: .
            dockerfile: Dockerfile.prod
        ports:
            - '80:80'
        environment:
            - NODE_ENV=production
